In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\Kirti\OneDrive\Desktop\Loan Default Prediction\data\raw\loan_dataset_20000.csv")

In [3]:
df.head(3)

,age,gender,marital_status,education_level,annual_income,monthly_income,employment_status,debt_to_income_ratio,credit_score,loan_amount,...,loan_term,installment,grade_subgrade,num_of_open_accounts,total_credit_limit,current_balance,delinquency_history,public_records,num_of_delinquencies,loan_paid_back
0,59,Male,Married,Master's,24240.19,2020.02,Employed,0.074,743,17173.72,...,36,581.88,B5,7,40833.47,24302.07,1,0,1,1
1,72,Female,Married,Bachelor's,20172.98,1681.08,Employed,0.219,531,22663.89,...,60,573.17,F1,5,27968.01,10803.01,1,0,3,1
2,49,Female,Single,High School,26181.80,2181.82,Employed,0.234,779,3631.36,...,60,76.32,B4,2,15502.25,4505.44,0,0,0,1

In [4]:
df.shape

(20000, 22)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   20000 non-null  int64
 1   gender                20000 non-null  object
 2   marital_status        20000 non-null  object
 3   education_level       20000 non-null  object
 4   annual_income         20000 non-null  float64
 5   monthly_income        20000 non-null  float64
 6   employment_status     20000 non-null  object
 7   debt_to_income_ratio  20000 non-null  float64
 8   credit_score          20000 non-null  int64
 9   loan_amount           20000 non-null  float64
 10  loan_purpose          20000 non-null  object
 11  interest_rate         20000 non-null  float64
 12  loan_term             20000 non-null  int64
 13  installment           20000 non-null  float64
 14  grade_subgrade        20000 non-null  object
 15  num_of_open_accounts  20000 non-null  int64
 16  total_credit_limit    20000 non-null  float64
 17  current_balance       20000 non-null  float64
 18  delinquency_history   20000 non-null  int64
 19  public_records        20000 non-null  int64
 20  num_of_delinquencies  20000 non-null  int64
 21  loan_paid_back        20000 non-null  int64
dtypes: float64(8), int64(8), object(6)
memory usage: 3.4+ MB

In [5]:
df.columns

Index(['age', 'gender', 'marital_status', 'education_level', 'annual_income',
       'monthly_income', 'employment_status', 'debt_to_income_ratio',
       'credit_score', 'loan_amount', 'loan_purpose', 'interest_rate',
       'loan_term', 'installment', 'grade_subgrade', 'num_of_open_accounts',
       'total_credit_limit', 'current_balance', 'delinquency_history',
       'public_records', 'num_of_delinquencies', 'loan_paid_back'],
      dtype='object')

In [6]:
df.isnull().sum()

age                     0
gender                  0
marital_status          0
education_level         0
annual_income           0
monthly_income          0
employment_status       0
debt_to_income_ratio    0
credit_score            0
loan_amount             0
loan_purpose            0
interest_rate           0
loan_term               0
installment             0
grade_subgrade          0
num_of_open_accounts    0
total_credit_limit      0
current_balance         0
delinquency_history     0
public_records          0
num_of_delinquencies    0
loan_paid_back          0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

Handling Categorical Columns

In [8]:
cat_cols=df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col]=df[col].str.strip().str.lower()

In [9]:
for col in cat_cols:
    print(col,df[col].unique())
    print("-"*60)

gender ['male' 'female' 'other']
------------------------------------------------------------
marital_status ['married' 'single' 'divorced' 'widowed']
------------------------------------------------------------
education_level ["master's" "bachelor's" 'high school' 'other' 'phd']
------------------------------------------------------------
employment_status ['employed' 'unemployed' 'self-employed' 'student' 'retired']
------------------------------------------------------------
loan_purpose ['car' 'debt consolidation' 'business' 'other' 'home' 'medical'
 'education' 'vacation']
------------------------------------------------------------
grade_subgrade ['b5' 'f1' 'b4' 'a5' 'd5' 'b1' 'b3' 'a3' 'c4' 'c3' 'c2' 'd4' 'd3' 'c1'
 'e3' 'f4' 'c5' 'f3' 'f5' 'a2' 'd2' 'a4' 'e5' 'd1' 'e1' 'e2' 'b2' 'e4'
 'f2' 'a1']
------------------------------------------------------------

In [11]:
df['loan_paid_back'].value_counts()

loan_paid_back
1    15998
0     4002
Name: count, dtype: int64

In [12]:
df.head(3)

,age,gender,marital_status,education_level,annual_income,monthly_income,employment_status,debt_to_income_ratio,credit_score,loan_amount,...,loan_term,installment,grade_subgrade,num_of_open_accounts,total_credit_limit,current_balance,delinquency_history,public_records,num_of_delinquencies,loan_paid_back
0,59,male,married,master's,24240.19,2020.02,employed,0.074,743,17173.72,...,36,581.88,b5,7,40833.47,24302.07,1,0,1,1
1,72,female,married,bachelor's,20172.98,1681.08,employed,0.219,531,22663.89,...,60,573.17,f1,5,27968.01,10803.01,1,0,3,1
2,49,female,single,high school,26181.80,2181.82,employed,0.234,779,3631.36,...,60,76.32,b4,2,15502.25,4505.44,0,0,0,1

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   20000 non-null  int64
 1   gender                20000 non-null  object
 2   marital_status        20000 non-null  object
 3   education_level       20000 non-null  object
 4   annual_income         20000 non-null  float64
 5   monthly_income        20000 non-null  float64
 6   employment_status     20000 non-null  object
 7   debt_to_income_ratio  20000 non-null  float64
 8   credit_score          20000 non-null  int64
 9   loan_amount           20000 non-null  float64
 10  loan_purpose          20000 non-null  object
 11  interest_rate         20000 non-null  float64
 12  loan_term             20000 non-null  int64
 13  installment           20000 non-null  float64
 14  grade_subgrade        20000 non-null  object
 15  num_of_open_accounts  20000 non-null  int64
 16  total_credit_limit    20000 non-null  float64
 17  current_balance       20000 non-null  float64
 18  delinquency_history   20000 non-null  int64
 19  public_records        20000 non-null  int64
 20  num_of_delinquencies  20000 non-null  int64
 21  loan_paid_back        20000 non-null  int64
dtypes: float64(8), int64(8), object(6)
memory usage: 3.4+ MB

In [14]:
df.to_csv(r"C:\Users\Kirti\OneDrive\Desktop\Loan Default Prediction\data\processed\cleaned_loan_data.csv",index=False)